name: Trigger On Master
on:
  push:
    branches:
      - master

permissions: 
  contents: write

jobs:
  run-shared:
    uses: robotkernel-hal/module_slcan/.github/workflows/build-deb.yaml@master
    secrets: inherit

